version       = "0.1.0"
author        = "levovix0"
description   = "2D GPU rendering library for graphical interfaces"
license       = "MIT"
srcDir        = "src"

requires "nim >= 2.2.4"
requires "chroma"
requires "vmath"
requires "opengl"
requires "shady"
